# Generated by Django 5.1.6 on 2025-02-12 00:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(default=72, verbose_name='Heart Rate')),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True, verbose_name='Blood Pressure')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)')),
                ('blood_sugar_level', models.PositiveIntegerField(blank=True, default=90, null=True, verbose_name='Blood Sugar Level (mg/dL)')),
                ('oxygen_saturation', models.PositiveIntegerField(default=98, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Oxygen Saturation (%)')),
                ('respiratory_rate', models.PositiveIntegerField(default=16, verbose_name='Respiratory Rate (breaths/min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Health File',
                'verbose_name_plural': 'User Health Files',
                'db_table': 'user_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
